{% set name = "dagster_dbt" %}
{% set version = "0.6.7.post0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name|replace('_', '-') }}/{{ name|replace('_', '-') }}-{{ version }}.tar.gz"
  sha256: 57ef6e885770afd89666a4e597040c4ca4fbb029b9a7f2f5ef73eef50dde3c7f

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - dagster {{ version }}.*

test:
  imports:
    - dagster_dbt

about:
  home: "https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-dbt"
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: "Package for Dagster dbt integration."

extra:
  recipe-maintainers:
    - conda-forge/dagster
